name: servicehub-backend

services:
  app:
    image: ianmark123/servicehub-backend
    ports:
      - "8000:8000"
    env_file:
      - /root/env/servicehub-backend/.env
    environment:
      NODE_ENV: production
      PORT: "8000"
    restart: unless-stopped
